#AWS db configuration
#spring.datasource.url=jdbc:mysql://localhost:3306/formfix?serverTimezone=UTC
#spring.datasource.username=formfixuser
#spring.datasource.password=formfix@12formfix
#spring.jpa.show-sql=true
#spring.jpa.generate-ddl=true
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect



#Local db configuration
spring.datasource.url=jdbc:mysql://localhost:3306/formfix?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=saten@12sung
spring.jpa.show-sql=true
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

#spring.h2.console.enabled=true
#spring.datasource.platform=h2
#spring.datasource.url=jdbc:h2:mem:firsthalf-db;MV_STORE=false
#spring.jpa.hibernate.ddl-auto=update


